### ISSUE TITLE
Crashes & Issues.

### ISSUE THREAD

**Issue by Darthscion55** [Weathercold/ExtraLogging#2]
I believe this mod is the cause of quite a few issues. When testing, I enabled each mod one by one, (after verifying files on steam) and as soon as I re-enabled this mod I was hit with an error. 

This error blocks access to the in-game Mod browser and when loaded with another mod, (untested) Schematic browser or New Console, causes the game to crash on load. 
Here is a screen shot of the error given when trying to access the in game mod-browser. 

![java_3tIq1pcJKi](https://github.com/Weathercold/ExtraLogging/assets/140124893/7e75a907-9ba3-452f-9c32-34831cea39a9)

And here is a crash log from earlier before some sting to see the cause of what was happening.

[crash-report-12_09_2023_16_05_38.txt](https://github.com/Weathercold/ExtraLogging/files/13625936/crash-report-12_09_2023_16_05_38.txt)
[crash-report-12_09_2023_16_12_53.txt](https://github.com/Weathercold/ExtraLogging/files/13625937/crash-report-12_09_2023_16_12_53.txt)
 
 I am also having issues downloading your other mod "Extra Logging 2" found here, from the in game Mod browser 
 https://github.com/weathercold/extra-logging I'll create another issue there.

**Comment by Weathercold** [comment]
This is the old version which I don't plan to support anymore.

**Comment by Darthscion55** [comment]
> This is the old version which I don't plan to support anymore.

Fair enough
